name: Daily Python Script Execution

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run-python-script:
    runs-on: ubuntu-latest # 使用Ubuntu最新版本的虚拟环境
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # 检出代码
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7 # 选择你需要的Python版本
    - name: Execute Python script
      run: python script.py # 执行你的Python脚本
